export const AuthTypes = {
  PASSWORD_MISMATCH: 'PASSWORD_MISMATCH',
  PASSWORD_MATCH: 'PASSWORD_MATCH',

  SIGNUP_STARTED: 'SIGNUP_STARTED',
  SIGNUP_ENDED: 'SIGNUP_ENDED',
  SIGNUP_ERROR: 'SIGNUP_ERROR',

  SIGNIN_STARTED: 'SIGNIN_STARTED',
  SIGNIN_ENDED: 'SIGNIN_ENDED',
  SIGNIN_ERROR: 'SIGNIN_ERROR',
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',

  SIGNOUT_STARTED: 'SIGNOUT_STARTED',
  SIGNOUT_ENDED: 'SIGNOUT_ENDED',
  SIGNOUT_ERROR: 'SIGNOUT_ERROR',

  PROFILE_LOADING: 'PROFILE_LOADING',
  PROFILE_LOADED: 'PROFILE_LOADED',
  PROFILE_ERROR: 'PROFILE_ERROR',
  SET_PROFILE: 'SET_PROFILE',

  SET_USER: 'SET_USER',
  SET_UNSUBSCRIBE: 'SET_UNSUBSCRIBE',
  SET_IS_MANAGER: 'SET_IS_MANAGER',

  RESET: 'RESET',
};
